CREATE DATABASE IF NOT EXISTS THACH;

USE THACH;

DROP TABLE IF EXISTS STUDENT;

CREATE TABLE IF NOT EXISTS STUDENT (
  id INT(100) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(50),
  PRIMARY KEY (id)
);